# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    serializer:
        enabled: true
        default_context:
            datetime_format: 'Y-m-d'

    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: session.handler.native_file

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
