name: app
type: 'php:8.2'

build:
  flavor: none
  commands:
    # Installe les dépendances PHP et JS
    - composer install --prefer-dist --no-progress --no-interaction
    - npm install
    - npm build

web:
  commands:
    start: 'php -d variables_order=EGPCS -S 0.0.0.0:8080 -t public'

  locations:
    '/':
      root: 'public'
      index: 'index.php'
      scripts: true
      allow: true

mounts:
  '/var': 'shared:files'

variables:
  env:
    APP_ENV: 'prod'
    APP_DEBUG: '0'

dependencies:
  php:
    ext-mysql: '*'
    ext-pdo_mysql: '*'
    ext-ctype: '*'
    ext-iconv: '*'
    ext-opcache: '*'
