version: "3.8"

services:
  database:
    image: mysql:8.4.5
    networks:
      - database_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:

networks:
  database_network:
    driver: bridge