name: Run PHPUnit Tests with Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports: ['3306:3306']

    env:
      APP_ENV: test
      APP_SECRET: ${{ secrets.APP_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3.17
          extensions: mbstring, pdo, pdo_mysql, apcu, intl, opcache, zip
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create .env.test
        run: |
          echo "APP_ENV=test" > .env.test
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env.test
          echo "DATABASE_URL=mysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@127.0.0.1:3306/${{ secrets.MYSQL_DATABASE }}" >> .env.test

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h 127.0.0.1 -uroot -p${{ secrets.MYSQL_PASSWORD }} --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run PHPUnit with coverage
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Check coverage threshold
        run: |
          COVERAGE=$(php -r '
            $xml = simplexml_load_file("coverage.xml");
            $metrics = $xml->project->metrics;
            $covered = (int)$metrics["coveredstatements"];
            $total = (int)$metrics["statements"];
            echo round(($covered / $total) * 100, 2);
          ')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Test coverage is below 80% ($COVERAGE%)"
            exit 1
          fi