name: Build and Deploy to Raspberry Pi

on:
  push:
    branches: [mep]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lowercase repository_owner
        id: lowercase
        run: echo "repo_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ steps.lowercase.outputs.repo_lower }}/cv-maker:latest .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ steps.lowercase.outputs.repo_lower }}/cv-maker:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Lowercase repository_owner
        id: lowercase
        run: echo "repo_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Write SSH key
        run: |
          echo "${{ secrets.RASPBERRY_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to Raspberry Pi using Docker Compose
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.RASPBERRY_USER }}@${{ secrets.RASPBERRY_HOST }} << 'EOF'
            set -e
            cd /home/${RASPBERRY_USER}/portfolio

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/${{ steps.lowercase.outputs.repo_lower }}/cv-maker:latest

            docker compose -f docker-compose-prod.yml up -d --remove-orphans
          EOF